define(['router','jquery','lazy'],function(Router,$){
    
    var mm = new Router()
    .route('#/home',function(req,next){
       
        require(['home/home.js'],function(home){
            home.add();
            home.get();
            home.img();
        })
    })
    .route('#/dest',function(req,next){
       require(['dest/dest.js'],function(dest){
            dest.add();
            dest.get();
            dest.img();
            dest.buy();
        })
    })
    .route('#/dest',function(req,next){
        $('#aa').html('<h1>购物车</h1>')
    })
    .route('#/brand',function(req,next){
        $('#aa').html('<h1>个人中心</h1>')
    })
    .route('#/buy',function(req,next){
        $('#aa').html('<h1>个人中心</h1>')
    })
    .route('#/korea',function(req,next){
        require(['dest/korea/korea.js'],function(korea){
           korea.add();
           korea.img();
        })
    })
     .route('#/hk',function(req,next){
        require(['dest/hk/hk.js'],function(hk){
           hk.add();
           hk.img();
        })
    })
    .route('#/us',function(req,next){
        require(['dest/us/us.js'],function(us){
           us.add();
           us.img();
        })
    })
    .route('#/france',function(req,next){
        require(['dest/france/france.js'],function(france){
           france.add();
           france.img();
        })
    })
    .route('#/australia',function(req,next){
        require(['dest/australia/australia.js'],function(australia){
           australia.add();
           australia.img();
        })
    })
    .route('#/uk',function(req,next){
        require(['dest/uk/uk.js'],function(uk){
           uk.add();
           uk.img();
        })
    })
    .route('#/thailand',function(req,next){
        require(['dest/thailand/thailand.js'],function(thailand){
           thailand.add();
           thailand.img();
        })
    })
    .route('#/taiwan',function(req,next){
        require(['dest/taiwan/taiwan.js'],function(taiwan){
           taiwan.add();
           taiwan.img();
        })
    })
     .route('#/ltaly',function(req,next){
        require(['dest/ltaly/ltaly.js'],function(ltaly){
           ltaly.add();
           ltaly.img();
        })
    })
    .route('#/germany',function(req,next){
        require(['dest/germany/germany.js'],function(germany){
           germany.add();
           germany.img();
        })
    })
})